# Generated by Django 4.2.1 on 2023-12-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblogAppV3", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
